#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub enum Category {
    Tickle,
    Slap,
    Poke,
    Pat,
    Neko,
    Meow,
    Lizard,
    Kiss,
    Hug,
    FoxGirl,
    Feed,
    Cuddle,
    NekoGif,
    Kemonomimi,
    Holo,
    Smug,
    Baka,
    Woof,
    Wallpaper,
    Goose,
    Gecg,
    Avatar,
    Waifu,
    EightBall,
    RandomHentaiGif,
    Pussy,
    NsfwNekoGif,
    Lewd,
    Lesbian,
    Kuni,
    Cumsluts,
    Classic,
    Boobs,
    Bj,
    Anal,
    NsfwAvatar,
    Yuri,
    Trap,
    Tits,
    GirlSoloGif,
    GirlSolo,
    PussyWankGif,
    PussyArt,
    LewdKemonomimi,
    Kitsune,
    Keta,
    HoloLewd,
    HoloEro,
    Hentai,
    Futanari,
    Femdom,
    FeetGif,
    EroFeet,
    Feet,
    Ero,
    EroKitsune,
    EroKemonomimi,
    EroNeko,
    EroYuri,
    CumArts,
    BlowJob,
    Spank,
    Gasm,
    #[deprecated(
        note = "always returns https://cdn.nekos.life/smallboobs/404.png; this is only here for completeness"
    )]
    SmallBoobs,
}

impl Category {
    /// Gets the path to append after [`BASEURL`]+ to make a request to get an image / gif url.
    /// # Examples
    /// ```rust
    /// # use nekoslife::{Category, SfwCategory};
    /// assert_eq!(Category::from(SfwCategory::Waifu).to_url_path(), "waifu");
    /// ```
    pub const fn to_url_path(self) -> &'static str {
        use Category::*;

        match self {
            Tickle => "tickle",
            Slap => "slap",
            Poke => "poke",
            Pat => "pat",
            Neko => "neko",
            Meow => "meow",
            Lizard => "lizard",
            Kiss => "kiss",
            Hug => "hug",
            FoxGirl => "fox_girl",
            Feed => "feed",
            Cuddle => "cuddle",
            NekoGif => "ngif",
            Kemonomimi => "kemonomimi",
            Holo => "holo",
            Smug => "smug",
            Baka => "baka",
            Woof => "woof",
            Wallpaper => "wallpaper",
            Goose => "goose",
            Gecg => "gecg",
            Avatar => "avatar",
            Waifu => "waifu",
            EightBall => "8ball",
            RandomHentaiGif => "Random_hentai_gif",
            Pussy => "pussy",
            NsfwNekoGif => "nsfw_neko_gif",
            Lewd => "lewd",
            Lesbian => "les",
            Kuni => "kuni",
            Cumsluts => "cum",
            Classic => "classic",
            Boobs => "boobs",
            Bj => "bj",
            Anal => "anal",
            NsfwAvatar => "nsfw_avatar",
            Yuri => "yuri",
            Trap => "trap",
            Tits => "tits",
            GirlSoloGif => "solog",
            GirlSolo => "solo",
            PussyWankGif => "pwankg",
            PussyArt => "pussy_jpg",
            LewdKemonomimi => "lewdkemo",
            Kitsune => "lewdk",
            Keta => "keta",
            HoloLewd => "hololewd",
            HoloEro => "holoero",
            Hentai => "hentai",
            Futanari => "futanari",
            Femdom => "femdom",
            FeetGif => "feetg",
            EroFeet => "erofeet",
            Feet => "feet",
            Ero => "ero",
            EroKitsune => "erok",
            EroKemonomimi => "erokemo",
            EroNeko => "eron",
            EroYuri => "eroyuri",
            CumArts => "cum_jpg",
            BlowJob => "blowjob",
            Spank => "spank",
            Gasm => "gasm",
            #[allow(deprecated)]
            SmallBoobs => "smallboobs",
        }
    }
}
