/// A nsfw category of images.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum NsfwCategory {
    RandomHentaiGif,
    Pussy,
    NekoGif,
    Neko,
    Lesbian,
    Kuni,
    Cumsluts,
    Classic,
    Boobs,
    Bj,
    Anal,
    Avatar,
    Yuri,
    Trap,
    Tits,
    GirlSoloGif,
    GirlSolo,
    PussyWankGif,
    PussyArt,
    Kemonomimi,
    Kitsune,
    Keta,
    Holo,
    HoloEro,
    Hentai,
    Futanari,
    Femdom,
    FeetGif,
    EroFeet,
    Feet,
    Ero,
    EroKitsune,
    EroKemonomimi,
    EroNeko,
    EroYuri,
    CumArts,
    BlowJob,
    Spank,
    Gasm,
}

impl NsfwCategory {
    pub fn to_url_path(self) -> &'static str {
        use NsfwCategory::*;
        match self {
            RandomHentaiGif => "/img/Random_hentai_gif",
            Pussy => "/img/pussy",
            NekoGif => "/img/nsfw_neko_gif",
            Neko => "/img/lewd",
            Lesbian => "/img/les",
            Kuni => "/img/kuni",
            Cumsluts => "/img/cum",
            Classic => "/img/classic",
            Boobs => "/img/boobs",
            Bj => "/img/bj",
            Anal => "/img/anal",
            Avatar => "/img/nsfw_avatar",
            Yuri => "/img/yuri",
            Trap => "/img/trap",
            Tits => "/img/tits",
            GirlSoloGif => "/img/solog",
            GirlSolo => "/img/solo",
            PussyWankGif => "/img/pwankg",
            PussyArt => "/img/pussy_jpg",
            Kemonomimi => "/img/lewdkemo",
            Kitsune => "/img/lewdk",
            Keta => "/img/keta",
            Holo => "/img/hololewd",
            HoloEro => "/img/holoero",
            Hentai => "/img/hentai",
            Futanari => "/img/futanari",
            Femdom => "/img/femdom",
            FeetGif => "/img/feetg",
            EroFeet => "/img/erofeet",
            Feet => "/img/feet",
            Ero => "/img/ero",
            EroKitsune => "/img/erok",
            EroKemonomimi => "/img/erokemo",
            EroNeko => "/img/eron",
            EroYuri => "/img/eroyuri",
            CumArts => "/img/cum_jpg",
            BlowJob => "/img/blowjob",
            Spank => "/img/spank",
            Gasm => "/img/gasm",
        }
    }
}
