/// A sfw category of images.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SfwCategory {
    Tickle,
    Slap,
    Poke,
    Pat,
    Neko,
    Meow,
    Lizard,
    Kiss,
    Hug,
    FoxGirl,
    Feed,
    Cuddle,
    Why,
    CatText,
    OwOify,
    EightBall,
    Fact,
    NekoGif,
    Kemonomimi,
    Holo,
    Smug,
    Baka,
    Woof,
    Spoiler,
    Wallpaper,
    Goose,
    Gecg,
    Avatar,
    Waifu,
}

impl SfwCategory {
    pub fn to_url_path(self) -> &'static str {
        use SfwCategory::*;
        match self {
            Tickle => "/img/tickle",
            Slap => "/img/slap",
            Poke => "/img/poke",
            Pat => "/img/pat",
            Neko => "/img/neko",
            Meow => "/img/meow",
            Lizard => "/img/lizard",
            Kiss => "/img/kiss",
            Hug => "/img/hug",
            FoxGirl => "/img/fox_girl",
            Feed => "/img/feed",
            Cuddle => "/img/cuddle",
            Why => "/why",
            CatText => "/cat",
            OwOify => "/owoify",
            EightBall => "/8ball",
            Fact => "/fact",
            NekoGif => "/img/ngif",
            Kemonomimi => "/img/kemonomimi",
            Holo => "/img/holo",
            Smug => "/img/smug",
            Baka => "/img/baka",
            Woof => "/img/woof",
            Spoiler => "/spoiler",
            Wallpaper => "/img/wallpaper",
            Goose => "/img/goose",
            Gecg => "/img/gecg",
            Avatar => "/img/avatar",
            Waifu => "/img/waifu",
        }
    }
}
